"""
Django settings for P_EcoPrenda project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
import pymysql
pymysql.install_as_MySQLdb()
# Configuración adicional de Cloudinary
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables del archivo .env
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Cambia a False en producción

ALLOWED_HOSTS = ['192.168.1.87', '127.0.0.1', 'localhost', 'proyectoecoprenda-ykp.onrender.com']

CSRF_TRUSTED_ORIGINS = [
    'https://proyectoecoprenda-ykp.onrender.com'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'A_EcoPrenda',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Middlewares personalizados para gestión de sesiones
    'A_EcoPrenda.middleware.SessionManagementMiddleware',
    'A_EcoPrenda.middleware.InactivityLogoutMiddleware',
    'A_EcoPrenda.middleware.SessionSecurityMiddleware',
    # Middlewares personalizados para cookies
    'A_EcoPrenda.cookie_middleware.CookieConsentMiddleware',
    'A_EcoPrenda.cookie_middleware.CookiePreferencesMiddleware',
]

ROOT_URLCONF = 'P_EcoPrenda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'P_EcoPrenda.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# PostgreSQL (Principal)
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DB_URL'),
        conn_max_age=600  # Opcional: para persistencia de conexión
    )
}

# MySQL (Secundaria) - Mantengo intacto para aprendizaje y requerimiento
DATABASES['mysql_db'] = dj_database_url.config(
    default=os.environ.get('MYSQL_ADDON_URI'),
    conn_max_age=600
)

DATABASE_ROUTERS = ['P_EcoPrenda.db_routers.AppRouter']

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'  # Sugerencia: Cambia a 'es' si la app es en español

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'Static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración para archivos de media (imágenes subidas por usuarios)
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL de login
LOGIN_URL = '/login/'

# Redirección después del login
LOGIN_REDIRECT_URL = 'home'

# Redirección después del logout
LOGOUT_REDIRECT_URL = 'home'

# Configuración de Sesiones

# Motor de sesiones (base de datos es más seguro que archivos)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Duración de la sesión (en segundos)
# 2 horas = 7200 segundos
# 24 horas = 86400 segundos
# 7 días = 604800 segundos
SESSION_COOKIE_AGE = 86400  # 24 horas

# Expirar sesión al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # False = mantiene la sesión según SESSION_COOKIE_AGE

# Nombre de la cookie de sesión
SESSION_COOKIE_NAME = 'ecoprenda_sessionid'

# Seguridad de cookies
SESSION_COOKIE_HTTPONLY = True  # No accesible desde JavaScript
SESSION_COOKIE_SECURE = False  # True solo en HTTPS (cambiar a True en producción)
SESSION_COOKIE_SAMESITE = 'Lax'  # Protección CSRF

# Serialización de sesiones
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'

# Configuración de Seguridad

# Protección CSRF
CSRF_COOKIE_HTTPONLY = False  # Debe ser False para que JavaScript pueda leerla
CSRF_COOKIE_SECURE = False  # True en producción con HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = 'ecoprenda_csrftoken'

# Headers de seguridad
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
# Agregado: Más headers para mayor seguridad
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Sugerencia: Mejora privacidad

# En producción, descomenta y activa estos (o usa un settings_prod.py separado):
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# ==============================================================================
# CONFIGURACIÓN DE APIs EXTERNAS - Agregar al final de settings.py
# ==============================================================================

# ---------------------- GEOAPIFY (Mapas) ----------------------
# Cambiado: Sin default hardcoded; requiere .env
GEOAPIFY_API_KEY = os.environ.get('GEOAPIFY_API_KEY')
if not GEOAPIFY_API_KEY:
    raise ValueError("GEOAPIFY_API_KEY no está definida en .env")

# ---------------------- CLOUDINARY (Imágenes) ----------------------
# Cambiado: Sin defaults hardcoded; requiere .env
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET')
}
# Valida que todas las claves estén presentes
for key in CLOUDINARY_STORAGE.values():
    if not key:
        raise ValueError("Una o más claves de CLOUDINARY no están definidas en .env")

# Usar Cloudinary como almacenamiento por defecto
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# ---------------------- CARBON INTERFACE (Impacto Ambiental) ----------------------
# Cambiado: Sin default hardcoded; requiere .env
CARBON_INTERFACE_API_KEY = os.environ.get('CARBON_INTERFACE_API_KEY')
if not CARBON_INTERFACE_API_KEY:
    raise ValueError("CARBON_INTERFACE_API_KEY no está definida en .env")

# Configuración de Cloudinary (mantengo, pero asegúrate de que no duplique)
cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME'),
    api_key=os.environ.get('CLOUDINARY_API_KEY'),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET'),
    secure=True  # Usar HTTPS
)

# Validación final: Asegura que claves críticas estén presentes (opcional, para debugging)
required_env_vars = ['DB_URL', 'MYSQL_ADDON_URI']  # Agrega más si necesitas
for var in required_env_vars:
    if not os.environ.get(var):
        raise ValueError(f"{var} no está definida en .env")
