"""
Django settings for P_EcoPrenda project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables del archivo .env
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!vv=3%%p7%(h*-3o2to1sc@s1&u2v0^-e!-bl-87g+npg5)xyb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.87','127.0.0.1','localhost','proyectoecoprenda-ykp.onrender.com']

CSRF_TRUSTED_ORIGINS = [
    'https://proyectoecoprenda-ykp.onrender.com'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'A_EcoPrenda',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Middlewares personalizados para gestión de sesiones
    'A_EcoPrenda.middleware.SessionManagementMiddleware',
    'A_EcoPrenda.middleware.InactivityLogoutMiddleware',
    'A_EcoPrenda.middleware.SessionSecurityMiddleware',
    # Middlewares personalizados para cookies
    'A_EcoPrenda.cookie_middleware.CookieConsentMiddleware',
    'A_EcoPrenda.cookie_middleware.CookiePreferencesMiddleware',
]

ROOT_URLCONF = 'P_EcoPrenda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'P_EcoPrenda.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# PostgreSQL (Principal)
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DB_URL'),
        conn_max_age=600 # Opcional: para persistencia de conexión
    )
}

# MySQL (Secundaria)
DATABASES['mysql_db'] = dj_database_url.config(
    default=os.environ.get('MYSQL_ADDON_URI'),
    conn_max_age=600
)

DATABASE_ROUTERS = ['P_EcoPrenda.db_routers.InventarioRouter']

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'Static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración para archivos de media (imágenes subidas por usuarios)
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL de login
LOGIN_URL = '/login/'

# Redirección después del login
LOGIN_REDIRECT_URL = 'home'

# Redirección después del logout
LOGOUT_REDIRECT_URL = 'home'

# Configuración de Sesiones

# Motor de sesiones (base de datos es más seguro que archivos)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Duración de la sesión (en segundos)
# 2 horas = 7200 segundos
# 24 horas = 86400 segundos
# 7 días = 604800 segundos
SESSION_COOKIE_AGE = 86400  # 24 horas

# Expirar sesión al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # False = mantiene la sesión según SESSION_COOKIE_AGE

# Guardar sesión en cada request (False = solo si se modifica)
SESSION_SAVE_EVERY_REQUEST = False

# Nombre de la cookie de sesión
SESSION_COOKIE_NAME = 'ecoprenda_sessionid'

# Seguridad de cookies
SESSION_COOKIE_HTTPONLY = True  # No accesible desde JavaScript
SESSION_COOKIE_SECURE = False  # True solo en HTTPS (cambiar a True en producción)
SESSION_COOKIE_SAMESITE = 'Lax'  # Protección CSRF

# Serialización de sesiones
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'

# Configuración de Seguridad

# Protección CSRF
CSRF_COOKIE_HTTPONLY = False  # Debe ser False para que JavaScript pueda leerla
CSRF_COOKIE_SECURE = False  # True en producción con HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = 'ecoprenda_csrftoken'

# Headers de seguridad
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# En producción, activar estos:
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
