# Generated by Django 5.2.5 on 2025-12-04 04:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo_contacto', models.EmailField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen_fundacion', models.ImageField(blank=True, help_text='Imagen o logo de la fundación', max_length=200, null=True, upload_to='fundaciones/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('lat', models.FloatField(blank=True, help_text='Latitud de la fundación (OBLIGATORIO para aparecer en mapa)', null=True)),
                ('lng', models.FloatField(blank=True, help_text='Longitud de la fundación (OBLIGATORIO para aparecer en mapa)', null=True)),
            ],
            options={
                'db_table': 'fundacion',
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('talla', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADA', 'Reservada'), ('EN_PROCESO_ENTREGA', 'En Proceso de Entrega'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('AGOTADA', 'Agotada')], default='DISPONIBLE', max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad disponible en stock')),
                ('imagen_prenda', models.ImageField(blank=True, max_length=200, null=True, upload_to='prendas/')),
            ],
            options={
                'db_table': 'prenda',
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipo_transaccion',
            },
        ),
        migrations.CreateModel(
            name='CampanaFundacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen_campana', models.ImageField(blank=True, max_length=200, null=True, upload_to='campanas/')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('objetivo_prendas', models.IntegerField(help_text='Meta de prendas a recolectar')),
                ('activa', models.BooleanField(default=True)),
                ('categorias_solicitadas', models.CharField(help_text='Categorías separadas por comas', max_length=300)),
                ('fundacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_EcoPrenda.fundacion')),
            ],
            options={
                'db_table': 'campana_fundacion',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('DONACION', 'Donación'), ('INTERCAMBIO', 'Intercambio'), ('VENTA', 'Venta'), ('IMPACTO', 'Impacto Ambiental'), ('COMUNIDAD', 'Comunidad')], max_length=20)),
                ('icono', models.CharField(help_text='Clase de ícono Bootstrap', max_length=50)),
                ('requisito_valor', models.IntegerField(help_text='Valor necesario para desbloquear')),
                ('codigo', models.CharField(default='', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'logro',
                'indexes': [models.Index(fields=['tipo'], name='logro_tipo_e7594a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImpactoAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbono_evitar_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('energia_ahorrada_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_calculo', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_EcoPrenda.prenda')),
            ],
            options={
                'db_table': 'impacto_ambiental',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=120, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('REPRESENTANTE_FUNDACION', 'Representante de Fundación'), ('MODERADOR', 'Moderador'), ('ADMINISTRADOR', 'Administrador')], default='CLIENTE', help_text='Rol del usuario en el sistema', max_length=30)),
                ('imagen_usuario', models.ImageField(blank=True, help_text='Imagen de perfil del usuario', max_length=200, null=True, upload_to='usuarios/')),
                ('es_staff', models.BooleanField(default=False, help_text='Puede acceder al panel de administración')),
                ('direccion', models.CharField(blank=True, help_text='Dirección completa del usuario', max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, help_text='Latitud para ubicación en mapa', null=True)),
                ('lng', models.FloatField(blank=True, help_text='Longitud para ubicación en mapa', null=True)),
                ('mostrar_en_mapa', models.BooleanField(default=False, help_text='¿Permitir que mi ubicación sea visible en el mapa público?')),
                ('fundacion_asignada', models.ForeignKey(blank=True, help_text='Fundación a la que representa (solo para representantes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representantes', to='A_EcoPrenda.fundacion')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RESERVADA', 'Reservada'), ('EN_PROCESO', 'En Proceso de Entrega'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada'), ('EN_DISPUTA', 'En Disputa'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('destino_final', models.CharField(blank=True, help_text='Destino final de la donación', max_length=300, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('en_disputa', models.BooleanField(default=False)),
                ('razon_disputa', models.TextField(blank=True, null=True)),
                ('fecha_disputa', models.DateTimeField(blank=True, null=True)),
                ('direccion_retiro', models.CharField(blank=True, help_text='Dirección de retiro/origen para envío', max_length=300, null=True)),
                ('direccion_entrega', models.CharField(blank=True, help_text='Dirección de entrega/destino para envío', max_length=300, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Peso estimado de la prenda en kilogramos', max_digits=5, null=True)),
                ('dimensiones', models.CharField(blank=True, help_text='Dimensiones del paquete (largo x ancho x alto en cm)', max_length=100, null=True)),
                ('codigo_seguimiento_envio', models.CharField(blank=True, help_text='Código de seguimiento del envío (Shipit u otro)', max_length=100, null=True)),
                ('costo_envio', models.DecimalField(blank=True, decimal_places=2, help_text='Costo del envío calculado', max_digits=10, null=True)),
                ('courier', models.CharField(blank=True, help_text='Nombre del courier (ej: Chilexpress, Correos, etc.)', max_length=50, null=True)),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='A_EcoPrenda.campanafundacion')),
                ('fundacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='A_EcoPrenda.fundacion')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_EcoPrenda.prenda')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_EcoPrenda.tipotransaccion')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputas_reportadas', to='A_EcoPrenda.usuario')),
                ('user_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_destino', to='A_EcoPrenda.usuario')),
                ('user_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_origen', to='A_EcoPrenda.usuario')),
            ],
            options={
                'db_table': 'transaccion',
            },
        ),
        migrations.AddField(
            model_name='prenda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_EcoPrenda.usuario'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500)),
                ('fecha_envio', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='A_EcoPrenda.usuario')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='A_EcoPrenda.usuario')),
            ],
            options={
                'db_table': 'mensaje',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='fundacion',
            name='representante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundacion_representada', to='A_EcoPrenda.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField(default=django.utils.timezone.now)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_EcoPrenda.logro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_EcoPrenda.usuario')),
            ],
            options={
                'db_table': 'usuario_logro',
            },
        ),
        migrations.AddIndex(
            model_name='campanafundacion',
            index=models.Index(fields=['activa'], name='campana_fun_activa_502162_idx'),
        ),
        migrations.AddIndex(
            model_name='campanafundacion',
            index=models.Index(fields=['fecha_inicio'], name='campana_fun_fecha_i_5e31fc_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='usuario_rol_537fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['correo'], name='usuario_correo_94dccf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['estado'], name='transaccion_estado_f065ba_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['fecha_transaccion'], name='transaccion_fecha_t_becce3_idx'),
        ),
        migrations.AddIndex(
            model_name='prenda',
            index=models.Index(fields=['estado'], name='prenda_estado_f86c10_idx'),
        ),
        migrations.AddIndex(
            model_name='prenda',
            index=models.Index(fields=['categoria'], name='prenda_categor_3725e5_idx'),
        ),
        migrations.AddIndex(
            model_name='fundacion',
            index=models.Index(fields=['activa'], name='fundacion_activa_441da6_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariologro',
            index=models.Index(fields=['fecha_desbloqueo'], name='usuario_log_fecha_d_04dae2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariologro',
            unique_together={('user', 'logro')},
        ),
    ]
