# Generated by Django 5.2.5 on 2025-11-18 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id_fundacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('correo_contacto', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen_fundacion', models.ImageField(blank=True, help_text='Imagen o logo de la fundación', max_length=200, null=True, upload_to='fundaciones/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fundacion',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id_logro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('DONACION', 'Donación'), ('INTERCAMBIO', 'Intercambio'), ('VENTA', 'Venta'), ('IMPACTO', 'Impacto Ambiental'), ('COMUNIDAD', 'Comunidad')], max_length=20)),
                ('icono', models.CharField(help_text='Clase de ícono Bootstrap', max_length=50)),
                ('requisito_valor', models.IntegerField(help_text='Valor necesario para desbloquear')),
                ('codigo', models.CharField(default='', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'logro',
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id_prenda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('talla', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADA', 'Reservada'), ('EN_PROCESO_ENTREGA', 'En Proceso de Entrega'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('AGOTADA', 'Agotada')], default='DISPONIBLE', max_length=50)),
                ('disponibilidad', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_PROCESO', 'En Proceso'), ('INTERCAMBIADA', 'Intercambiada'), ('VENDIDA', 'Vendida'), ('DONADA', 'Donada'), ('NO_DISPONIBLE', 'No Disponible')], default='DISPONIBLE', max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad disponible en stock')),
                ('imagen_prenda', models.ImageField(blank=True, max_length=200, null=True, upload_to='prendas/')),
            ],
            options={
                'db_table': 'prenda',
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipo_transaccion',
            },
        ),
        migrations.CreateModel(
            name='CampanaFundacion',
            fields=[
                ('id_campana', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen_campana', models.ImageField(blank=True, max_length=200, null=True, upload_to='campanas/')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('objetivo_prendas', models.IntegerField(help_text='Meta de prendas a recolectar')),
                ('activa', models.BooleanField(default=True)),
                ('categorias_solicitadas', models.CharField(help_text='Categorías separadas por comas', max_length=300)),
                ('id_fundacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_EcoPrenda.fundacion')),
            ],
            options={
                'db_table': 'campana_fundacion',
            },
        ),
        migrations.CreateModel(
            name='ImpactoAmbiental',
            fields=[
                ('id_impacto', models.AutoField(primary_key=True, serialize=False)),
                ('carbono_evitar_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('energia_ahorrada_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_calculo', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_prenda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='A_EcoPrenda.prenda')),
            ],
            options={
                'db_table': 'impacto_ambiental',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(max_length=120, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('REPRESENTANTE_FUNDACION', 'Representante de Fundación'), ('MODERADOR', 'Moderador'), ('ADMINISTRADOR', 'Administrador')], default='CLIENTE', help_text='Rol del usuario en el sistema', max_length=30)),
                ('imagen_usuario', models.ImageField(blank=True, help_text='Imagen de perfil del usuario', max_length=200, null=True, upload_to='usuarios/')),
                ('es_staff', models.BooleanField(default=False, help_text='Puede acceder al panel de administración')),
                ('fundacion_asignada', models.ForeignKey(blank=True, help_text='Fundación a la que representa (solo para representantes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representantes', to='A_EcoPrenda.fundacion')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_transaccion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RESERVADA', 'Reservada'), ('EN_PROCESO', 'En Proceso de Entrega'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada'), ('EN_DISPUTA', 'En Disputa'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('destino_final', models.CharField(blank=True, help_text='Destino final de la donación', max_length=300, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('en_disputa', models.BooleanField(default=False)),
                ('razon_disputa', models.TextField(blank=True, null=True)),
                ('fecha_disputa', models.DateTimeField(blank=True, null=True)),
                ('id_campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='A_EcoPrenda.campanafundacion')),
                ('id_fundacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='A_EcoPrenda.fundacion')),
                ('id_prenda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='A_EcoPrenda.prenda')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='A_EcoPrenda.tipotransaccion')),
                ('id_usuario_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaccion_id_usuario_destino_set', to='A_EcoPrenda.usuario')),
                ('id_usuario_origen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaccion_id_usuario_origen_set', to='A_EcoPrenda.usuario')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputas_reportadas', to='A_EcoPrenda.usuario')),
            ],
            options={
                'db_table': 'transaccion',
            },
        ),
        migrations.AddField(
            model_name='prenda',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='A_EcoPrenda.usuario'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=500)),
                ('fecha_envio', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_emisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mensaje_id_emisor_set', to='A_EcoPrenda.usuario')),
                ('id_receptor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mensaje_id_receptor_set', to='A_EcoPrenda.usuario')),
            ],
            options={
                'db_table': 'mensaje',
            },
        ),
        migrations.AddField(
            model_name='fundacion',
            name='representante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundacion_representada', to='A_EcoPrenda.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioLogro',
            fields=[
                ('id_usuario_logro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_desbloqueo', models.DateTimeField(default=django.utils.timezone.now)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_EcoPrenda.logro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_EcoPrenda.usuario')),
            ],
            options={
                'db_table': 'usuario_logro',
                'unique_together': {('usuario', 'logro')},
            },
        ),
    ]
