# Generated by Django 5.2.5 on 2025-12-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_EcoPrenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundacion',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitud de la fundación (OBLIGATORIO para aparecer en mapa)', null=True),
        ),
        migrations.AddField(
            model_name='fundacion',
            name='lng',
            field=models.FloatField(blank=True, help_text='Longitud de la fundación (OBLIGATORIO para aparecer en mapa)', null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='codigo_seguimiento_envio',
            field=models.CharField(blank=True, help_text='Código de seguimiento del envío (Shipit u otro)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='costo_envio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo del envío calculado', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='courier',
            field=models.CharField(blank=True, help_text='Nombre del courier (ej: Chilexpress, Correos, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='dimensiones',
            field=models.CharField(blank=True, help_text='Dimensiones del paquete (largo x ancho x alto en cm)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='direccion_entrega',
            field=models.CharField(blank=True, help_text='Dirección de entrega/destino para envío', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='direccion_retiro',
            field=models.CharField(blank=True, help_text='Dirección de retiro/origen para envío', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso estimado de la prenda en kilogramos', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección completa del usuario', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitud para ubicación en mapa', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lng',
            field=models.FloatField(blank=True, help_text='Longitud para ubicación en mapa', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mostrar_en_mapa',
            field=models.BooleanField(default=False, help_text='¿Permitir que mi ubicación sea visible en el mapa público?'),
        ),
    ]
