# Generated by Django 5.2.5 on 2025-12-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_EcoPrenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundacion',
            name='id',
        ),
        migrations.AddField(
            model_name='fundacion',
            name='id_fundacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
